		<h3>Step 2: generating providers.xml file</h3>
        <p>Here is the autogenerated providers.xml file for your webserver.<br>
        You can briefly modify it before applying it to your server. This will be the one<br>
        you will provide to clients that wants to connect (will it be desktop, web etc..)</p>
        <p>This configuration will also be responsible for /v1/config OCS call!</p>
        
        <form action="/admin/steps/step2" method="post">
			<table border="0">
				<tr><td>Server ID</td><td><input type="text" name="serverid" value="<?=$data[0]['serverid']?>" placeholder="id (e.g. myocsserver)"></td></tr>
				<tr><td>Name</td><td><input type="text" name="name" value="<?=$data[0]['name']?>" placeholder="name (e.g. My Ocs Server)"></td></tr>
				<tr><td>Website URL</td><td><input type="text" name="website" value="<?=$data[0]['website']?>" placeholder="website (e.g. myocsserver.com)"></td></tr>
				<tr><td>Host</td><td><input type="text" name="host" value="<?=$data[0]['host']?>" placeholder="host (e.g. ocs.myocsserver.com)"></td></tr>
				<tr><td>V1 location</td><td><input type="text" name="location" value="<?=$data[0]['location']?>" placeholder="v1 (e.g. ocs.myocsserver.com/v1)"></td></tr>
				<tr><td>Terms of use URL</td><td><input type="text" name="termsofuse" value="<?=$data[0]['termsofuse']?>" placeholder="link to terms of use"></td></tr>
				<tr><td>Register new user URL</td><td><input type="text" name="register" value="<?=$data[0]['register']?>" placeholder="link to page registration"></td></tr>
				<tr><td>E-mail of admin</td><td><input type="text" name="contact" value="<?=$data[0]['contact']?>" placeholder="email of server admin"></td></tr>
				
				<tr><td><label for="sslid">Protocol:</label></td><td>
					<select id="sslid" name="ssl">
						<option value="no" <?=$data[0]['ssln']?>>http</option>
						<option value="yes" <?=$data[0]['ssly']?>>https</option>
					</select>
				</td></tr>
				<tr><td><label for="formatid">Output:</label></td>
					<td>
					<select id="formatid" name="format">
						<option value="xml" <?=$data[0]['jsonn']?>>xml</option>
						<option value="json" <?=$data[0]['jsony']?>>json</option>
					</select>
				</td></tr>
				
				<tr><td colspan="2"><input style="float:right" type="submit" value="Generate configuration"></td></tr>
			</table>
        </form>
		<hr>
		<h4>Generated providers.xml:</h4>
		<pre>
			<?=$data[0]['exampleprovider']?>
		</pre>
		<hr>
		<h4>/v1/config call:</h4>
		<pre>
			<?=$data[0]['configcall']?>
		</pre>
		<hr>
		<form action="/admin/steps/step2/save">
			<input type="submit" value="Save config and proceed">
		</form>
